mysql:
  host: 'mysql_db'
  port: 3306
  user: 'root'
  password: 'admin'

clickhouse:
  host: 'clickhouse_db'
  port: 9123
  user: 'default'
  password: 'admin'

binlog_replicator:
  data_dir: '/app/binlog/'
  records_per_file: 100000

databases: 'test_replication'

target_databases:
  test_replication: test_replication_ch
