
mysql:
  host: 'mysql_db'
  port: 3306
  user: 'root'
  password: 'admin'

clickhouse:
  host: 'clickhouse_db'
  port: 9123
  user: 'default'
  password: 'admin'

binlog_replicator:
  data_dir: '/root/binlog/'
  records_per_file: 1000

databases: '*test*'
log_level: 'info'
optimize_interval: 3
check_db_updated_interval: 3
