
mysql:
  host: 'localhost'
  port: 9307
  user: 'root'
  password: 'admin'

clickhouse:
  host: 'localhost'
  port: 9123
  user: 'default'
  password: 'admin'

binlog_replicator:
  data_dir: '/app/binlog/'
  records_per_file: 100000

databases: '*test*'
log_level: 'debug'
optimize_interval: 3
check_db_updated_interval: 3


partition_bys:
  - databases: 'replication-test_db'
    tables: ['test_table']
    partition_by: 'intDiv(id, 1000000)'

